# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWQ4MDQ2ZTgxNDAwZTAxOTVkNjVjZmI5ODk2NTA4ZmYyNjliMGRjMDdlMTA3ZDQ3YjNlZjcyNjgwYTllMTM3YzM4YzQ5ZDQzNjk2NTk0NTc5NzVhMWIwOTQzOTc1YzA4YjAwYmM0NGMwMzllYjZhMjJjZTdjNDU0YmVmMDUwMzU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
