#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MzU0ODVhOWMwZDczYzA1ZmI5M2NmZDc1NDM1NDRlNGU0NDFmMmExMTJiYzJjYWZjYjkzMzk3MTg2M2NhZmNmYzMwNjMzMjk2NDk0ZGJiNzFhMzU4MTQxNTExZGFjYWIzZmQ0MQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
