#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTAzNjQyYjFlOWY4YTUyNmM0MmI0ZTAxYmJiYzMxYmFmYTRhZDE0YTVmMmNiM2VmNzI5ZDUzNTRkOThjODljNzIzY2MwZDc2ZjlkNDEzYWY0ZjIzOTAzMmU1NjljM2UwZDE4Mg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
